// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzqysgsqxbvjnhzwefxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cXlzZ3NxeGJ2am5oendlZnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzk4NTksImV4cCI6MjA1Nzk1NTg1OX0.xFzsHkws7o_znmLPrr2h6N2mwDexAburxzECFNxelhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);